spring:
  profiles:
    group:
      default: local
      local: localdb, common, console-logging
      dev: devdb, common, file-logging
      prod: proddb, common, file-logging
---
spring:
  config:
    activate:
      on-profile: file-logging
---
spring:
  config:
    activate:
      on-profile: console-logging
---
spring:
  config:
    activate:
      on-profile: localdb
    import: classpath:schedule-task.yml
  datasource:
    url: jdbc:h2:mem:batch
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
  h2:
    console:
      path: /h2console
      enabled: true
logging:
  level:
    root: debug
---
spring:
  config:
    activate:
      on-profile: devdb
logging:
  level:
    root: debug
---
spring:
  config:
    activate:
      on-profile: proddb
logging:
  level:
    root: warn
---
spring:
  config:
    activate:
      on-profile: common
  jpa:
    open-in-view: false
  task:
    execution:
      pool:
        core-size: 8
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format_sql: true


