spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:batch
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
  h2:
    console:
      path: /h2console
      enabled: true

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format_sql: true
